# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#extra comment koos
Stylist.create(name: 'Angel', image_url:'angel.jpg')
Stylist.create(name: 'Mandy', image_url:'many.jpg')
Stylist.create(name: 'Marco', image_url:'marco.jpg')
Stylist.create(name: 'Michael', image_url:'michael.jpg')
Stylist.create(name: 'Patricia', image_url:'Patrica.jpg')
Stylist.create(name: 'Ruben', image_url:'ruben.jpg')
Stylist.create(name: 'Suzi', image_url:'Suzi.jpg')
Stylist.create(name: 'Jason', image_url:'jason.jpg')
Stylist.create(name: 'Thomas', image_url:'thomas.jpg')

Client.create(firstName: 'Angelique', lastName:'Smith', image_url:'AngeliqueSmith.jpg', sex:'female', stylist_id: 1)
Client.create(firstName: 'Anna', lastName:'George', image_url:'AnnaGeorge.jpg', sex:'female' , stylist_id: 2)
Client.create(firstName: 'Bibi', lastName:'Bahrain', image_url:'BibiBahrain.jpg', sex:'female', stylist_id: 3)
Client.create(firstName: 'Courtney', lastName:'Cooper', image_url:'CourtneyCooper.jpg', sex:'female', stylist_id: 4)
Client.create(firstName: 'Elle', lastName:'Taylor', image_url:'ElleTaylor.jpg', sex:'female', stylist_id: 5)
Client.create(firstName: 'Elve', lastName:'Short', image_url:'ElveShort.jpg', sex:'female', stylist_id: 6)
Client.create(firstName: 'Gita', lastName:'Smothers', image_url:'GitaSmothers.jpg', sex:'female', stylist_id: 7)
Client.create(firstName: 'Jean', lastName:'Smile', image_url:'JeanSmile.jpg', sex:'female', stylist_id: 8)
Client.create(firstName: 'Joanne', lastName:'Smolder', image_url:'JoanneSmolder.jpg', sex:'female', stylist_id: 9)
Client.create(firstName: 'Joanne', lastName:'Styler', image_url:'JoanneStyler.jpg', sex:'female', stylist_id: 1)
Client.create(firstName: 'Joan', lastName:'Rivera', image_url:'JoanRivera.jpg', sex:'female', stylist_id: 2)
Client.create(firstName: 'Jo', lastName:'Lo', image_url:'JoLo.jpg', sex:'female', stylist_id: 3)
Client.create(firstName: 'Me', lastName:'Am', image_url:'MeAm.jpg', sex:'female', stylist_id: 4)
Client.create(firstName: 'Mi', lastName:'Li', image_url:'MiLi.jpg', sex:'female', stylist_id: 5)
Client.create(firstName: 'Mina', lastName:'Mika', image_url:'MinaMika.jpg', sex:'female', stylist_id: 6)
Client.create(firstName: 'Patricia', lastName:'Wild', image_url:'PatriciaWild.jpg', sex:'female', stylist_id: 7)
Client.create(firstName: 'Prudence', lastName:'Clever', image_url:'PrudenceClever.jpg', sex:'female', stylist_id: 8)
Client.create(firstName: 'Sarah', lastName:'Fluenta', image_url:'SarahFluenta.jpg', sex:'female', stylist_id: 9)
Client.create(firstName: 'See', lastName:'Me', image_url:'SeeMe.jpg', sex:'female', stylist_id: 1)
Client.create(firstName: 'Sigourney', lastName:'Dreams', image_url:'SigourneyDreams.jpg', sex:'female', stylist_id: 1)
Client.create(firstName: 'Smiley', lastName:'Schoombe', image_url:'SmileySchoombe.jpg', sex:'female', stylist_id: 1)
Client.create(firstName: 'Snow', lastName:'White', image_url:'SnowWhite.jpg', sex:'female', stylist_id: 1)
Client.create(firstName: 'Sue', lastName:'Anne', image_url:'SueAnne.jpg', sex:'female', stylist_id: 3)
Client.create(firstName: 'Sue', lastName:'Style', image_url:'SueStyle.jpg', sex:'female', stylist_id: 4)
Client.create(firstName: 'Wilson', lastName:'Duns', image_url:'WilsonDuns.jpg', sex:'male', stylist_id: 4)
Client.create(firstName: 'Wilco', lastName:'Brand', image_url:'WilcoBrand.jpg', sex:'male', stylist_id: 4)
Client.create(firstName: 'Steve', lastName:'Taylor', image_url:'SteveTaylor.jpg', sex:'male', stylist_id: 1)
Client.create(firstName: 'Smiley', lastName:'Johnson', image_url:'SmileyJohnson.jpg', sex:'male', stylist_id: 5)
Client.create(firstName: 'Sanjeev', lastName:'Ghordan', image_url:'SanjeevGhordan.jpg', sex:'male', stylist_id: 5)
Client.create(firstName: 'Miles', lastName:'Away', image_url:'MilesAway.jpg', sex:'male', stylist_id: 5)
Client.create(firstName: 'Mi', lastName:'Jong', image_url:'MiJong.jpg', sex:'male', stylist_id: 7)
Client.create(firstName: 'Lee', lastName:'Caps', image_url:'LeeCaps.jpg', sex:'male', stylist_id: 7)
Client.create(firstName: 'John', lastName:'Baptist', image_url:'JohnBaptist.jpg', sex:'male', stylist_id: 9)
Client.create(firstName: 'Jo', lastName:'Hart', image_url:'JoHart.jpg', sex:'male', stylist_id: 9)
Client.create(firstName: 'Jason', lastName:'Borg', image_url:'JasonBorg.jpg', sex:'male', stylist_id: 9)
Client.create(firstName: 'Jan', lastName:'Jean', image_url:'JanJean.jpg', sex:'male', stylist_id: 9)
Client.create(firstName: 'Graig', lastName:'Jones', image_url:'GraigJones.jpg', sex:'male', stylist_id: 9)
Client.create(firstName: 'Dean', lastName:'Shout', image_url:'DeanShout.jpg', sex:'male', stylist_id: 1)
Client.create(firstName: 'Dave', lastName:'Becks', image_url:'DaveBecks.jpg', sex:'male', stylist_id: 6)
Client.create(firstName: 'Col', lastName:'Farrino', image_url:'ColFarrino.jpg', sex:'male', stylist_id: 6)
Client.create(firstName: 'Brad', lastName:'Coops', image_url:'BradCoops.jpg', sex:'male', stylist_id: 8)
Client.create(firstName: 'Angelo', lastName:'Pitts', image_url:'AngeloPitts.jpg', sex:'male', stylist_id: 8)

Service.create(name: 'Style', description: "The styling, cut of a clients har, including a wash", price: 150, duration:60)
Service.create(name: 'Cut', description: "The styling, cut of a clients har, including a wash", price: 150, duration:60)
Service.create(name: 'Blowdry', description: "The styling, cut of a clients har, including a wash", price: 150, duration:60)
Service.create(name: 'Colour', description: "The styling, cut of a clients har, including a wash", price: 150, duration:60)
Service.create(name: 'Braids', description: "The styling, cut of a clients har, including a wash", price: 150, duration:60)


Booking.create(date: DateTime.parse("01/11/2016 9:00"), status: "New", stylist_id: 1, service_id: 1, client_id: 1)